const photo=(id,w=800)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;
const drinks=[
{name:'The flat white',price:'4.50',category:'hot',tag:'THE EVERYDAY FAVORITE',notes:'Velvety milk. A beautifully bold little finish.',image:'photo-1570968915860-54d5c301fa9f',detail:'A double shot of espresso with silky, finely textured milk. Balanced, comforting, and a very good reason to get out of bed. Choose dairy or oat milk when you visit.'},
{name:'Honey oat iced latte',price:'5.50',category:'iced',tag:'A LITTLE SWEET SPOT',notes:'Golden honey. Creamy oat. All kinds of good.',image:'photo-1517701604599-bb29b565090c',detail:'Espresso over ice, creamy oat milk, and a gentle touch of honey. Smooth and lightly sweet, with all the space for the coffee to shine. Contains honey; choose our maple alternative for a plant-based cup.'},
{name:'Orange espresso tonic',price:'5.00',category:'special',tag:'SOMETHING UNEXPECTED',notes:'Bright citrus. A little fizz. A fresh perspective.',image:'photo-1461023058943-07fcbe16d735',detail:'Fresh espresso poured over chilled tonic, finished with a slice of orange. A sparkling balance of sweet and bitter for the curious coffee drinker.'},
{name:'Slow Sunday pour-over',price:'5.00',category:'hot',tag:'TAKE YOUR TIME',notes:'Single origin. Patiently poured. Worth the pause.',image:'photo-1495474472287-4d71bcdd2085',detail:'A freshly ground single-origin coffee, brewed by hand to draw out its natural sweetness and delicate aromas. Ask about the beans on our brew bar.'},
{name:'Easygoing cold brew',price:'4.50',category:'iced',tag:'KEEP IT COOL',notes:'Slow-steeped. Smooth. A sunny-day staple.',image:'photo-1517959105821-eaf2591984ca',detail:'Coffee steeped slowly in cool water for a rounded, mellow cup. Served over ice, with your choice of milk or simply as it comes.'},
{name:'The maple cloud',price:'5.50',category:'special',tag:'YOUR NEW LITTLE OBSESSION',notes:'Maple warmth. Silky foam. A dreamy finish.',image:'photo-1541167760496-1628856ab772',detail:'Our signature espresso with maple sweetness, silky milk, and a soft dusting of cinnamon. A comforting little departure from the ordinary.'}
];
const grid=document.querySelector('#drink-grid');
function renderMenu(category='all'){const selection=category==='all'?drinks.slice(0,3):drinks.filter(d=>d.category===category);grid.innerHTML=selection.map(d=>`<article class="drink-card"><div class="drink-photo"><img loading="lazy" src="${photo(d.image)}" alt="${d.name}"><span class="drink-tag">${d.tag}</span><button aria-label="Explore ${d.name}" data-drink="${drinks.indexOf(d)}">↗</button></div><div class="drink-info"><h3>${d.name}</h3><span>$${d.price}</span></div><p>${d.notes}</p></article>`).join('')}
renderMenu();
const tabs=[...document.querySelectorAll('[role=tab]')];tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>{tabs.forEach(t=>{t.setAttribute('aria-selected',String(t===tab));t.tabIndex=t===tab?0:-1});renderMenu(tab.dataset.category)});tab.tabIndex=i===0?0:-1;tab.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[n].focus();tabs[n].click()}})});
const modal=document.querySelector('#modal'),content=document.querySelector('#modal-content');function show(html){content.innerHTML=html;if(!modal.open)modal.showModal()}document.querySelector('.close-modal').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()}});
function showDrink(d,match=false){show(`<div class="eyebrow">${match?'YOUR COFFEE SOULMATE':d.tag}</div><img class="modal-image" src="${photo(d.image)}" alt="${d.name}"><h2>${d.name}</h2><p>${d.detail}</p><p><strong>$${d.price}</strong> · Made fresh, just for you.</p><button class="button" id="visit-from-modal">Get opening updates <span>↗</span></button>`);document.querySelector('#visit-from-modal').onclick=()=>{modal.close();document.querySelector('#visit').scrollIntoView({behavior:'smooth'})}}
grid.addEventListener('click',e=>{const button=e.target.closest('[data-drink]');if(button)showDrink(drinks[Number(button.dataset.drink)])});
let currentFeature=0;const features=[{name:'The everyday flat white',desc:'Small cup. Big main-character energy.',image:'photo-1442512595331-e89e73853f31'},{name:'A little honey, over ice',desc:'Your daily ritual, with a golden little twist.',image:'photo-1517701604599-bb29b565090c'},{name:'Good things take their time',desc:'Slow down. There’s a whole world in your cup.',image:'photo-1495474472287-4d71bcdd2085'}];const dots=[...document.querySelectorAll('.image-pagination button')];function setFeature(i){currentFeature=i;const f=features[i];document.querySelector('#featured-name').textContent=f.name;document.querySelector('#featured-desc').textContent=f.desc;const img=document.querySelector('#hero-image');img.src=photo(f.image,1400);img.alt=f.name;dots.forEach((d,n)=>{d.classList.toggle('active',n===i);d.setAttribute('aria-pressed',String(n===i))})}document.querySelector('#next-drink').onclick=()=>setFeature((currentFeature+1)%features.length);dots.forEach((d,i)=>d.onclick=()=>setFeature(i));
let temperature='';document.querySelector('#open-quiz').onclick=()=>{show(`<div class="eyebrow">THE COFFEE MATCH · 01 / 02</div><h2>How do you like<br>to take a moment?</h2><p>There’s no wrong answer. Just your kind of good.</p><div class="quiz-options"><button data-temp="hot">☀ Warm and cozy</button><button data-temp="iced">❄ Cool and refreshing</button><button data-temp="special">✳ Surprise me a little</button></div>`)};
content.addEventListener('click',e=>{const temp=e.target.closest('[data-temp]');if(temp){temperature=temp.dataset.temp;show(`<div class="eyebrow">THE COFFEE MATCH · 02 / 02</div><h2>And your flavor<br>state of mind?</h2><p>Follow your taste buds.</p><div class="quiz-options"><button data-flavor="classic">Keep it pure. Let the coffee shine.</button><button data-flavor="sweet">A little sweet makes my day.</button><button data-flavor="curious">Something I haven’t tried before.</button></div>`)}const flavor=e.target.closest('[data-flavor]');if(flavor){const f=flavor.dataset.flavor;const index=temperature==='hot'?(f==='sweet'?5:f==='curious'?3:0):temperature==='iced'?(f==='sweet'?1:f==='curious'?2:4):(f==='sweet'?5:f==='classic'?3:2);showDrink(drinks[index],true)}});
const articles={cascara:{title:'The other side of coffee.',body:'Before it’s a bean, coffee is a fruit. Cascara is the dried outer skin of that fruit, steeped like tea. Its flavors can recall dried cherries, hibiscus, or raisins, depending on the origin and preparation. Try it warm for a cozy afternoon cup, or over ice with a squeeze of citrus. Coffee still has a few surprises up its sleeve.'},pour:{title:'Make room for a slower cup.',body:'A pour-over puts a little patience at the center of your ritual. Start with 15 grams of medium-ground coffee and 250 grams of hot water. Rinse your paper filter, add the coffee, and pour just enough water to wet the grounds. Give it about 30 seconds to bloom, then slowly add the rest in small circles. Adjust the grind and pour to taste. That’s the lovely thing: the next cup is yours to explore.'},tonic:{title:'Your coffee. With a little sparkle.',body:'Fill a tall glass with ice and add around 120 ml of chilled tonic water. Slowly pour a fresh shot of espresso over the ice and finish with an orange slice. Taste before stirring, then give it a gentle mix. Try different tonics or swap orange for grapefruit to find your own balance. A refreshing little experiment for a sunny afternoon.'}};document.querySelectorAll('.learn').forEach(b=>b.onclick=()=>{const a=articles[b.dataset.topic];show(`<div class="eyebrow">A LITTLE COFFEE CURIOSITY</div><h2>${a.title}</h2><p>${a.body}</p>`)});
document.querySelector('#signup').addEventListener('submit',e=>{e.preventDefault();const email=document.querySelector('#email').value;try{localStorage.setItem('orlast-opening-interest',email);document.querySelector('#signup-status').textContent='Your interest is saved on this device. Our mailing list is coming soon.'}catch{document.querySelector('#signup-status').textContent='Our mailing list is coming soon. Drop by again for opening news.'}});
const toggle=document.querySelector('.mobile-toggle');toggle.onclick=()=>{const opened=document.querySelector('nav').classList.toggle('open');toggle.setAttribute('aria-expanded',String(opened));toggle.setAttribute('aria-label',opened?'Close navigation':'Open navigation')};document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('nav').classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
document.querySelector('#year').textContent=new Date().getFullYear();if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('js-reveal');observer.observe(el)})}
